# dbt profiles - copy to ~/.dbt/profiles.yml or set DBT_PROFILES_DIR
datapulse_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: edgodalle
      password: ''
      dbname: datapulse
      schema: public
      threads: 4
    
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 4

